import { Platform } from 'react-native';
import type { Theme } from './types';

const MONO = Platform.OS === 'ios' ? 'Courier New' : 'monospace';

export const darkTerminalTheme: Theme = {
  id: 'dark-terminal',
  name: 'Dark Terminal',
  description: 'Deep navy · monospace',
  dark: true,
  previewSwatches: ['#080E1A', '#0C1526', '#4AFFB4', '#4AB8FF'],
  subjectPanel: 'list'    as const,
  progressChart: 'colordots'   as const,
  checkedIn: 'Percent' as const,
  colors: {
    screenBg: '#080E1A',
    cardBg: '#0C1526',
    cardBorder: '#152035',
    textPrimary: '#E4EEF7',
    textSecondary: '#6ACAFF',
    textMuted: '#5A8AB0',
    accent: '#4AFFB4',
    accentSecondary: '#4AB8FF',
    buttonPrimaryBg: '#4AFFB4',
    buttonPrimaryText: '#080E1A',
    tabBarBg: '#0C1526',
    tabBarBorderTop: '#1E3450',
    tabBarActiveTint: '#4AFFB4',
    tabBarInactiveTint: '#4A7090',
    inputBg: '#0C1526',
    inputBorder: '#1E3450',
    inputText: '#E4EEF7',
    profileCardBg: '#0C1526',
    profileCardText: '#E4EEF7',
    profileCardMeta: '#5A8AB0',
    profileBadgeBg: '#1E3450',
    profileBadgeText: '#6ACAFF',
    headerBg: '#080E1A',
    headerText: '#4AFFB4',
    headerBorderBottom: '#1E3450',
    headerBackBg: '#0C1526',
    headerBackIcon: '#4AFFB4',
    sectionLabel: '#5A8AB0',
    divider: '#1E3450',
    pillSwitcherBg: '#0C1526',
    pillActiveBg: '#1E3450',
    pillActiveText: '#4AFFB4',
    pillInactiveText: '#5A8AB0',
  },
  fonts: {
    heading: MONO,
    body: MONO,
    headingWeight: '700',
    bodyWeight: '400',
    letterSpacingHeading: -0.5,
  },
  radii: {
    card: 8,
    button: 8,
    input: 6,
    tile: 8,
    pill: 4,
  },
};
