import type { Theme } from './types';

export const defaultTheme: Theme = {
  id: 'default',
  name: 'Default',
  description: 'Clean & minimal',
  dark: false,
  previewSwatches: ['#F2F2F7', '#1C1C1E', '#185FA5', '#1D9E75'],
  subjectPanel: 'tile'  as const,
  progressChart: 'barchart' as const,
  checkedIn: 'CtoT' as const,
  colors: {
    screenBg: '#F2F2F7',
    cardBg: '#FFFFFF',
    cardBorder: '#E0E0E6',
    textPrimary: '#1C1C1E',
    textSecondary: '#555555',
    textMuted: '#AAAAAA',
    accent: '#185FA5',
    accentSecondary: '#1D9E75',
    buttonPrimaryBg: '#1C1C1E',
    buttonPrimaryText: '#FFFFFF',
    tabBarBg: '#FFFFFF',
    tabBarBorderTop: '#F0F0F0',
    tabBarActiveTint: '#1C1C1E',
    tabBarInactiveTint: '#C7C7CC',
    inputBg: '#F5F5F5',
    inputBorder: '#EBEBEB',
    inputText: '#1C1C1E',
    profileCardBg: '#1C1C1E',
    profileCardText: '#FFFFFF',
    profileCardMeta: '#AAAAAA',
    profileBadgeBg: '#2C2C2E',
    profileBadgeText: '#98D7C2',
    headerBg: '#F2F2F7',
    headerText: '#1C1C1E',
    headerBorderBottom: 'transparent',
    headerBackBg: '#F0F0F5',
    headerBackIcon: '#1C1C1E',
    sectionLabel: '#888888',
    divider: '#F0F0F0',
    pillSwitcherBg: '#E0E0E8',
    pillActiveBg: '#FFFFFF',
    pillActiveText: '#1C1C1E',
    pillInactiveText: '#888888',
  },
  fonts: {
    heading: undefined,
    body: undefined,
    headingWeight: '700',
    bodyWeight: '500',
    letterSpacingHeading: -0.3,
  },
  radii: {
    card: 16,
    button: 16,
    input: 14,
    tile: 16,
    pill: 20,
  },
};
