import type { Theme } from './types';

export const softFocusTheme: Theme = {
  id: 'soft-focus',
  name: 'Soft Focus',
  description: 'Warm terracotta · cozy',
  dark: false,
  previewSwatches: ['#FDF8F4', '#FFFFFF', '#D96B3F', '#7B9E6E'],
  subjectPanel: 'tile'  as const,
  progressChart: 'barchart' as const,
  checkedIn: 'CtoT' as const,
  colors: {
    screenBg: '#FDF8F4',
    cardBg: '#FFFFFF',
    cardBorder: '#EDE0D8',
    textPrimary: '#2D1F1A',
    textSecondary: '#8A7060',
    textMuted: '#BBA89C',
    accent: '#D96B3F',
    accentSecondary: '#7B9E6E',
    buttonPrimaryBg: '#2D1F1A',
    buttonPrimaryText: '#FFFFFF',
    tabBarBg: '#FDF8F4',
    tabBarBorderTop: '#EDE0D8',
    tabBarActiveTint: '#D96B3F',
    tabBarInactiveTint: '#BBA89C',
    inputBg: '#FFFFFF',
    inputBorder: '#EDE0D8',
    inputText: '#2D1F1A',
    profileCardBg: '#2D1F1A',
    profileCardText: '#FFFFFF',
    profileCardMeta: '#8A7060',
    profileBadgeBg: '#D96B3F',
    profileBadgeText: '#FFFFFF',
    headerBg: '#FDF8F4',
    headerText: '#2D1F1A',
    headerBorderBottom: 'transparent',
    headerBackBg: '#F0E8E2',
    headerBackIcon: '#2D1F1A',
    sectionLabel: '#BBA89C',
    divider: '#EDE0D8',
    pillSwitcherBg: '#EDE0D8',
    pillActiveBg: '#FFFFFF',
    pillActiveText: '#2D1F1A',
    pillInactiveText: '#BBA89C',
  },
  fonts: {
    heading: undefined,
    body: undefined,
    headingWeight: '700',
    bodyWeight: '600',
    letterSpacingHeading: 0,
  },
  radii: {
    card: 20,
    button: 18,
    input: 16,
    tile: 20,
    pill: 24,
  },
};
