import type { Theme } from './types';

export const teenEnergyTheme: Theme = {
  id: 'teen-energy',
  name: 'Teen Energy',
  description: 'Dark · neon · high contrast',
  dark: true,
  previewSwatches: ['#0D0D0F', '#16161A', '#C8FF00', '#FF3CAC'],
  subjectPanel: 'list'    as const,
  progressChart: 'progressline' as const,
  checkedIn: 'Percent' as const,
  colors: {
    screenBg: '#0D0D0F',
    cardBg: '#16161A',
    cardBorder: '#2A2A30',
    textPrimary: '#FFFFFF',
    textSecondary: '#AAAAAA',
    textMuted: '#555555',
    accent: '#C8FF00',
    accentSecondary: '#FF3CAC',
    buttonPrimaryBg: '#C8FF00',
    buttonPrimaryText: '#0D0D0F',
    tabBarBg: '#16161A',
    tabBarBorderTop: '#2A2A30',
    tabBarActiveTint: '#C8FF00',
    tabBarInactiveTint: '#444444',
    inputBg: '#16161A',
    inputBorder: '#2A2A30',
    inputText: '#FFFFFF',
    profileCardBg: '#1A1A22',
    profileCardText: '#FFFFFF',
    profileCardMeta: '#555555',
    profileBadgeBg: '#1E2A00',
    profileBadgeText: '#C8FF00',
    headerBg: '#0D0D0F',
    headerText: '#C8FF00',
    headerBorderBottom: '#2A2A30',
    headerBackBg: '#1A1A22',
    headerBackIcon: '#C8FF00',
    sectionLabel: '#444444',
    divider: '#2A2A30',
    pillSwitcherBg: '#1A1A22',
    pillActiveBg: '#2A2A30',
    pillActiveText: '#C8FF00',
    pillInactiveText: '#444444',
  },
  fonts: {
    heading: undefined,
    body: undefined,
    headingWeight: '900',
    bodyWeight: '700',
    letterSpacingHeading: -1,
  },
  radii: {
    card: 14,
    button: 14,
    input: 12,
    tile: 14,
    pill: 20,
  },
};
